### ISSUE TITLE
Should i be on a specific openwrt version for this to work ???

### ISSUE THREAD

**Issue by karimHI** [xchwarze/frieren#5]
2024-11-01 08:54:22 [INFO] OpenWRT system detected, proceeding with installation...
2024-11-01 08:54:23 [ERROR] Error: Failed to obtain package URL for version 17 (Exit Code: 1)

im on openwrt 17.4

**Comment by m5kro** [comment]
Try openwrt 19.07, that seems to work for me.

Edit: The script checks for openwrt 19 or above

```
get_package_url() {
    local version="$1"
    local package_url=""

    if [ "$version" = "19" ]; then
        package_url="${BASE_URL}/19/${PACKAGE_NAME}_latest.ipk"
    elif [ "$version" -ge 20 ]; then
        package_url="${BASE_URL}/latest/${PACKAGE_NAME}_latest.ipk"
    fi

    echo "$package_url"
}
```

**Comment by xchwarze** [comment]
What kind of monster use openwrt 17? the only versions that are supported by OpenWRT are 22 and 23.
The only reason why Frieren supports older versions is to be able to install it on hak5 pineapples and use it as an alternative panel.

**Comment by karimHI** [comment]
i use it just for QOS

**Comment by karimHI** [comment]
btw i did install 19.7 and it's working thanks
